
-- step 1: create database
CREATE OR REPLACE DATABASE IMT577_DB_COLE_THORPEN;

-- step 2: create data warehouse
CREATE OR REPLACE WAREHOUSE IMT577_DW_COLE_THORPEN WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 600 AUTO_RESUME = TRUE COMMENT = '';

-- CHANGE THE WORKSPACE FOR DW SCHEMA IF NECESSARY
USE WAREHOUSE IMT577_DW_COLE_THORPEN;

-- step 3: create a snowflake stage for all tables
-- CHANNEL 
CREATE OR REPLACE STAGE "IMT577_DB_COLE_THORPEN"."PUBLIC".CHANNEL_STAGE URL = 'azure://sp72storage.blob.core.windows.net/channel' CREDENTIALS = (AZURE_SAS_TOKEN = '?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2026-04-23T10:59:43Z&st=2022-04-23T02:59:43Z&spr=https,http&sig=uWPc88FzwC98%2BdzbqdTHprs2ON%2FhAzK7m2Hrig8w9G8%3D');

-- CHANNEL CATEGORY
CREATE OR REPLACE STAGE "IMT577_DB_COLE_THORPEN"."PUBLIC".CHANNEL_CATEGORY_STAGE URL = 'azure://sp72storage.blob.core.windows.net/channelcategory' CREDENTIALS = (AZURE_SAS_TOKEN = '?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2026-04-23T10:59:43Z&st=2022-04-23T02:59:43Z&spr=https,http&sig=uWPc88FzwC98%2BdzbqdTHprs2ON%2FhAzK7m2Hrig8w9G8%3D');

-- CUSTOMER
CREATE OR REPLACE STAGE "IMT577_DB_COLE_THORPEN"."PUBLIC".CUSTOMER_STAGE URL = 'azure://sp72storage.blob.core.windows.net/customer' CREDENTIALS = (AZURE_SAS_TOKEN = '?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2026-04-23T10:59:43Z&st=2022-04-23T02:59:43Z&spr=https,http&sig=uWPc88FzwC98%2BdzbqdTHprs2ON%2FhAzK7m2Hrig8w9G8%3D');


-- PRODUCT
CREATE OR REPLACE STAGE "IMT577_DB_COLE_THORPEN"."PUBLIC".PRODUCT_STAGE URL = 'azure://sp72storage.blob.core.windows.net/product' CREDENTIALS = (AZURE_SAS_TOKEN = '?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2026-04-23T10:59:43Z&st=2022-04-23T02:59:43Z&spr=https,http&sig=uWPc88FzwC98%2BdzbqdTHprs2ON%2FhAzK7m2Hrig8w9G8%3D');


-- PRODUCT CATEGORY
CREATE OR REPLACE STAGE "IMT577_DB_COLE_THORPEN"."PUBLIC".PRODUCT_CATEGORY_STAGE URL = 'azure://sp72storage.blob.core.windows.net/productcategory' CREDENTIALS = (AZURE_SAS_TOKEN = '?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2026-04-23T10:59:43Z&st=2022-04-23T02:59:43Z&spr=https,http&sig=uWPc88FzwC98%2BdzbqdTHprs2ON%2FhAzK7m2Hrig8w9G8%3D');

-- PRODUCT TYPE
CREATE OR REPLACE STAGE "IMT577_DB_COLE_THORPEN"."PUBLIC".PRODUCT_TYPE_STAGE URL = 'azure://sp72storage.blob.core.windows.net/producttype' CREDENTIALS = (AZURE_SAS_TOKEN = '?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2026-04-23T10:59:43Z&st=2022-04-23T02:59:43Z&spr=https,http&sig=uWPc88FzwC98%2BdzbqdTHprs2ON%2FhAzK7m2Hrig8w9G8%3D');

-- RESELLER
CREATE OR REPLACE STAGE "IMT577_DB_COLE_THORPEN"."PUBLIC".RESELLER_STAGE URL = 'azure://sp72storage.blob.core.windows.net/reseller' CREDENTIALS = (AZURE_SAS_TOKEN = '?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2026-04-23T10:59:43Z&st=2022-04-23T02:59:43Z&spr=https,http&sig=uWPc88FzwC98%2BdzbqdTHprs2ON%2FhAzK7m2Hrig8w9G8%3D');

-- SALES DETAIL
CREATE OR REPLACE STAGE "IMT577_DB_COLE_THORPEN"."PUBLIC".SALES_DETAIL_STAGE URL = 'azure://sp72storage.blob.core.windows.net/salesdetail' CREDENTIALS = (AZURE_SAS_TOKEN = '?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2026-04-23T10:59:43Z&st=2022-04-23T02:59:43Z&spr=https,http&sig=uWPc88FzwC98%2BdzbqdTHprs2ON%2FhAzK7m2Hrig8w9G8%3D');

-- SALES HEADER 
CREATE OR REPLACE STAGE "IMT577_DB_COLE_THORPEN"."PUBLIC".SALES_HEADER_STAGE URL = 'azure://sp72storage.blob.core.windows.net/salesheader' CREDENTIALS = (AZURE_SAS_TOKEN = '?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2026-04-23T10:59:43Z&st=2022-04-23T02:59:43Z&spr=https,http&sig=uWPc88FzwC98%2BdzbqdTHprs2ON%2FhAzK7m2Hrig8w9G8%3D');

-- STORE
CREATE OR REPLACE STAGE "IMT577_DB_COLE_THORPEN"."PUBLIC".STORE_STAGE URL = 'azure://sp72storage.blob.core.windows.net/store' CREDENTIALS = (AZURE_SAS_TOKEN = '?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2026-04-23T10:59:43Z&st=2022-04-23T02:59:43Z&spr=https,http&sig=uWPc88FzwC98%2BdzbqdTHprs2ON%2FhAzK7m2Hrig8w9G8%3D');

-- TARGET DATA CHANNEL RESELLER AND STORE
CREATE OR REPLACE STAGE "IMT577_DB_COLE_THORPEN"."PUBLIC".TARGET_DATA_CHANNEL_STAGE URL = 'azure://sp72storage.blob.core.windows.net/targetdatachannel' CREDENTIALS = (AZURE_SAS_TOKEN = '?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2026-04-23T10:59:43Z&st=2022-04-23T02:59:43Z&spr=https,http&sig=uWPc88FzwC98%2BdzbqdTHprs2ON%2FhAzK7m2Hrig8w9G8%3D');

-- TARGET DATA PRODUCT 
CREATE OR REPLACE STAGE "IMT577_DB_COLE_THORPEN"."PUBLIC".TARGET_DATA_PRODUCT_STAGE URL = 'azure://sp72storage.blob.core.windows.net/targetdataproduct' CREDENTIALS = (AZURE_SAS_TOKEN = '?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2026-04-23T10:59:43Z&st=2022-04-23T02:59:43Z&spr=https,http&sig=uWPc88FzwC98%2BdzbqdTHprs2ON%2FhAzK7m2Hrig8w9G8%3D');

-- step 4: create a file format using the FILE FORMAT comman to describe the format of the file to be imported
CREATE OR REPLACE FILE FORMAT CSV_SKIP_HEADER
type = 'CSV'
field_delimiter = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
skip_header = 1;

-- step 5: create tables
-- CHANNEL
CREATE OR REPLACE TABLE STAGE_CHANNEL (
    CHANNELID NUMBER(38,0),
    CHANNELCATEGORYID NUMBER(38,0),
    CHANNEL VARCHAR(255),
    CREATEDDATE VARCHAR(255),
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE VARCHAR(255),
    MODIFIEDBY VARCHAR(255)
);

-- CHANNEL_CATEGORY
CREATE OR REPLACE TABLE STAGE_CHANNEL_CATEGORY (
    CHANNELCATEGORYID NUMBER(38,0),
    CHANNELCATEGORY VARCHAR(255),
    CREATEDDATE VARCHAR(255),
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE VARCHAR(255),
    MODIFIEDBY VARCHAR(255)
);

-- CUSTOMER
CREATE OR REPLACE TABLE STAGE_CUSTOMER (
    CUSTOMERID VARCHAR(255),
    SUBSEGMENT NUMBER(28,0),
    FIRSTNAME VARCHAR(255),
    LASTNAME VARCHAR(255),
    GENDER VARCHAR(255),
    EMAILADDRESS VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(255),
    STATEPROVINCE VARCHAR(255),
    COUNTRY VARCHAR(255),
    POSTALCODE VARCHAR(255),
    PHONENUMBER VARCHAR(255),
    CREATEDDATE VARCHAR(255),
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE VARCHAR(255),
    MODIFIEDBY VARCHAR(255)
);

-- PRODUCT
CREATE OR REPLACE TABLE STAGE_PRODUCT (
    PRODUCTID NUMBER(38,0),
    PRODUCTTYPEID NUMBER(38,0),
    PRODUCT VARCHAR(255),
    COLOR VARCHAR(255),
    STYLE VARCHAR(255),
    UNITOFMEASUREID NUMBER(38,0),
    WEIGHT FLOAT,
    PRICE FLOAT, 
    COST FLOAT, 
    CREATEDDATE VARCHAR(255),
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE VARCHAR(255),
    MODIFIEDBY VARCHAR(255),
    WHOLESALEPRICE FLOAT
);

-- PRODUCT_CATEGORY
CREATE OR REPLACE TABLE STAGE_PRODUCT_CATEGORY (
    PRODUCTCATEGORYID NUMBER(38,0),
    PRODUCTCATEGORY VARCHAR(255),
    CREATEDDATE VARCHAR(255),
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE VARCHAR(255),
    MODIFIEDBY VARCHAR(255)
);

-- PRODUCT_TYPE
CREATE OR REPLACE TABLE STAGE_PRODUCT_TYPE (
    PRODUCTTYPEID NUMBER(38,0),
    PRODUCTCATEGORYID NUMBER(38,0),
    PRODUCTTYPE VARCHAR(255),
    CREATEDDATE VARCHAR(255),
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE VARCHAR(255),
    MODIFIEDBY VARCHAR(255)
);

-- RESELLER
CREATE OR REPLACE TABLE STAGE_RESELLER (
    RESELLERID VARCHAR(255),
    CONTACT VARCHAR(255),
    EMAILADDRESS VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(255),
    STATEPROVINCE VARCHAR(255),
    COUNTRY VARCHAR(255),
    POSTALCODE VARCHAR(255),
    PHONENUMBER VARCHAR(255),
    CREATEDDATE VARCHAR(255),
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE VARCHAR(255),
    MODIFIEDBY VARCHAR(255),
    RESELLERNAME VARCHAR(255)
);

-- SALES_DETAIL
CREATE OR REPLACE TABLE STAGE_SALES_DETAIL (
    SALESDETAILID NUMBER(38,0),
    SALESHEADERID NUMBER(38,0),
    PRODUCTID NUMBER(38,0),
    SALESQUANTITY NUMBER(38,0),
    SALESAMOUNT FLOAT,
    CREATEDDATE VARCHAR(255),
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE VARCHAR(255),
    MODIFIEDBY VARCHAR(255)
);

-- SALES_HEADER
CREATE OR REPLACE TABLE STAGE_SALES_HEADER (
    SALESHEADERID NUMBER(38,0),
    DATE VARCHAR(255),
    CHANNELID NUMBER(38,0),
    STOREID NUMBER(38,0),
    CUSTOMERID VARCHAR(255),
    RESELLERID VARCHAR(255),
    CREATEDDATE VARCHAR(255),
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE VARCHAR(255),
    MODIFIEDBY VARCHAR(255)
);

-- STORE
CREATE OR REPLACE TABLE STAGE_STORE (
    STOREID VARCHAR(255),
    SUBSEGMENT NUMBER(38,0),
    STORENUMBER NUMBER(38,0),
    STOREMANAGER VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(255),
    STATEPROVINCE VARCHAR(255),
    COUNTRY VARCHAR(255),
    POSTALCODE VARCHAR(255),
    PHONENUMBER VARCHAR(255),
    CREATEDDATE VARCHAR(255),
    CREATEDBY VARCHAR(255),
    MODIFIEDDATE VARCHAR(255),
    MODIFIEDBY VARCHAR(255)
);

-- TARGET_DATA_CHANNEL
CREATE OR REPLACE TABLE STAGE_TARGET_DATA_CHANNEL (
    YEAR NUMBER(38,0),
    CHANNELNAME VARCHAR(255),
    TARGETNAME VARCHAR(255),
    TARGETSALESAMOUNT FLOAT
);

-- TARGET_DATA_PRODUCT
CREATE OR REPLACE TABLE STAGE_TARGET_DATA_PRODUCT (
    PRODUCTID NUMBER(38,0),
    PRODUCT VARCHAR(255),
    YEAR NUMBER(38,0),
    SALESQUANTITYTARGET FLOAT
);

-- step 6: copy data into stage > table
-- CHANNEL
COPY INTO "IMT577_DB_COLE_THORPEN"."PUBLIC"."STAGE_CHANNEL" FROM '@"IMT577_DB_COLE_THORPEN"."PUBLIC"."CHANNEL_STAGE"' FILE_FORMAT = '"IMT577_DB_COLE_THORPEN"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

-- CHANNEL_CATEGORY
COPY INTO "IMT577_DB_COLE_THORPEN"."PUBLIC"."STAGE_CHANNEL_CATEGORY" FROM '@"IMT577_DB_COLE_THORPEN"."PUBLIC"."CHANNEL_CATEGORY_STAGE"' FILE_FORMAT = '"IMT577_DB_COLE_THORPEN"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

-- CUSTOMER
COPY INTO "IMT577_DB_COLE_THORPEN"."PUBLIC"."STAGE_CUSTOMER" FROM '@"IMT577_DB_COLE_THORPEN"."PUBLIC"."CUSTOMER_STAGE"' FILE_FORMAT = '"IMT577_DB_COLE_THORPEN"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

-- PRODUCT
COPY INTO "IMT577_DB_COLE_THORPEN"."PUBLIC"."STAGE_PRODUCT" FROM '@"IMT577_DB_COLE_THORPEN"."PUBLIC"."PRODUCT_STAGE"' FILE_FORMAT = '"IMT577_DB_COLE_THORPEN"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

-- PRODUCT_CATEGORY
COPY INTO "IMT577_DB_COLE_THORPEN"."PUBLIC"."STAGE_PRODUCT_CATEGORY" FROM '@"IMT577_DB_COLE_THORPEN"."PUBLIC"."PRODUCT_CATEGORY_STAGE"' FILE_FORMAT = '"IMT577_DB_COLE_THORPEN"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

-- PRODUCT_TYPE
COPY INTO "IMT577_DB_COLE_THORPEN"."PUBLIC"."STAGE_PRODUCT_TYPE" FROM '@"IMT577_DB_COLE_THORPEN"."PUBLIC"."PRODUCT_TYPE_STAGE"' FILE_FORMAT = '"IMT577_DB_COLE_THORPEN"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

-- RESELLER
COPY INTO "IMT577_DB_COLE_THORPEN"."PUBLIC"."STAGE_RESELLER" FROM '@"IMT577_DB_COLE_THORPEN"."PUBLIC"."RESELLER_STAGE"' FILE_FORMAT = '"IMT577_DB_COLE_THORPEN"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

-- SALES_DETAIL
COPY INTO "IMT577_DB_COLE_THORPEN"."PUBLIC"."STAGE_SALES_DETAIL" FROM '@"IMT577_DB_COLE_THORPEN"."PUBLIC"."SALES_DETAIL_STAGE"' FILE_FORMAT = '"IMT577_DB_COLE_THORPEN"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

-- SALES_HEADER
COPY INTO "IMT577_DB_COLE_THORPEN"."PUBLIC"."STAGE_SALES_HEADER" FROM '@"IMT577_DB_COLE_THORPEN"."PUBLIC"."SALES_HEADER_STAGE"' FILE_FORMAT = '"IMT577_DB_COLE_THORPEN"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

-- STORE
COPY INTO "IMT577_DB_COLE_THORPEN"."PUBLIC"."STAGE_STORE" FROM '@"IMT577_DB_COLE_THORPEN"."PUBLIC"."STORE_STAGE"' FILE_FORMAT = '"IMT577_DB_COLE_THORPEN"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

-- TARGET_DATA_CHANNEL
COPY INTO "IMT577_DB_COLE_THORPEN"."PUBLIC"."STAGE_TARGET_DATA_CHANNEL" FROM '@"IMT577_DB_COLE_THORPEN"."PUBLIC"."TARGET_DATA_CHANNEL_STAGE"' FILE_FORMAT = '"IMT577_DB_COLE_THORPEN"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;

-- TARGET_DATA_PRODUCT
COPY INTO "IMT577_DB_COLE_THORPEN"."PUBLIC"."STAGE_TARGET_DATA_PRODUCT" FROM '@"IMT577_DB_COLE_THORPEN"."PUBLIC"."TARGET_DATA_PRODUCT_STAGE"' FILE_FORMAT = '"IMT577_DB_COLE_THORPEN"."PUBLIC"."CSV_SKIP_HEADER"' ON_ERROR = 'ABORT_STATEMENT' PURGE = FALSE;


-- SELECTS
SELECT * FROM STAGE_CHANNEL;
SELECT * FROM STAGE_CHANNEL_CATEGORY;
SELECT * FROM STAGE_CUSTOMER;
SELECT * FROM STAGE_PRODUCT;
SELECT * FROM STAGE_PRODUCT_CATEGORY;
SELECT * FROM STAGE_PRODUCT_TYPE;
SELECT * FROM STAGE_RESELLER;
SELECT * FROM STAGE_SALES_DETAIL;
SELECT * FROM STAGE_SALES_HEADER;
SELECT * FROM STAGE_STORE;
SELECT * FROM STAGE_TARGET_DATA_CHANNEL;
SELECT * FROM STAGE_TARGET_DATA_PRODUCT;

--CLEAN UP
-- DROP DATABASE IMT577_DB_COLE_THORPEN;
-- DROP WAREHOUSE IMT577_DW_COLE_THORPEN;






